### ISSUE TITLE
Server name being stripped from URL for sub directories

### ISSUE THREAD

**Issue by jasonculligan** [oupala/apaxy#80] opened 2016-11-30 23:14 UTC
Apache2 on Ubuntu 16.04, /var/www/html contains the standard index.html location.  I place .htaccess and theme in this folder and I can see the CSS styling works nicely.  However there is a subfolder I use also in /var/www/html and when I hover over the subfolder icon 'http://servername/' gets stripped from the URL (http://servername/subfolder) and the URL just becomes 'subfolder' so I can't reach the subfolder.  I can access the subfolder fine if I just manually enter 'http://servername/subfolder' myself.  Also only happens with Chrome.  Works fine with IE

**Comment by duncanplatt** [comment] 2016-12-02 02:14
Hi @jasonculligan, I've found this solution fixes it. I'm too new at git to submit a pull request, unfortunately, so I'm tagging @AdamWhitcroft for his attention.

I've narrowed the problem down to theme/footer.html on line 20:
Change this line:
`        while (i--){
            var a = indexes[i].getElementsByTagName('a')[0];
            a.href = '/' + uri + '/' + a.getAttribute('href',2);
        }`

so that it matches:
`        while (i--){
            var a = indexes[i].getElementsByTagName('a')[0];
            a.href = '.' + uri + '/' + a.getAttribute('href',2);
        }`

Notably, the _a.href = '/'_ should change to _a.href = '.'_

You are now good to go.

**Comment by AdamWhitcroft** [comment] 2016-12-02 08:22
Thanks for that @duncanplatt, pinging @oupala to verify.

**Comment by oupala** [comment] 2016-12-02 23:10
I'm sorry to say that I don't have Chrome. I can't test the usecase.

**Comment by ijavid** [comment] 2016-12-21 19:54
I've faced the same problem on my enviroment, using a virtual host for public directoty listing [link](http://public.ijavid.eu/). 
In root directory link are generated like `//subfolder/` which is evaluated by browser (chrome) as a [protocol-less hiperlink](http://stackoverflow.com/questions/6785442/browser-support-for-urls-beginning-with-double-slash)

I'm suggesting the following solution:
`a.href = uri ? '/' : '' + uri + '/' + a.getAttribute('href',2);`
this generates urls in root folder with one slash

**Comment by PHR16384** [comment] 2017-01-26 19:51
Just letting you guys know that the above "fix" (via the js script appended to footer.html) causes the exact same problem when I test my server locally.  "localhost:[port]" is stripped out and all my links are changed to "http://[subfolder_name]" and "http://[filename]".

Is this still an issue without that script on www hosted servers?  If so, I'd suggest changing the fix to prepend all file/subfolder hrefs with the current URL, and prepend the "Parent Directory" link with the server IP.

**Comment by oupala** [comment] 2017-01-27 10:48
I finally tested it with Chrome, and it appears that I can't reproduce the problem.

I'm using the develop branch, without further modification to any js.

Do you have any public instance of apaxy where I can test and try to reproduce the problem with my Chrome?

**Comment by SystemRevolution** [comment] 2017-02-17 16:56
i've fund a possible origin of the problem.
Try to change all `theme/` to `/theme/` (but Apaxy should be installed on root directory, I think).

**Comment by oupala** [comment] 2017-02-17 20:16
Ok. This problem has already been found, and fixed by a pull request (see #78).

This pull request has already been merged into branch *develop*. So try to install *develop* branch in order to check if it fixes your problem. And **no**, it does not mean you have to install apaxy in the root folder. Just edit the configuration to fit your needs:

`/{FOLDERNAME}/theme/`

**Comment by PHR16384** [comment] 2017-02-24 19:01
- Switching to the dev branch didn't help.  Mostly because the .htaccess templates of each branch are identical (except for comments).
- When viewing server subfolders (when I type them into the URL bar manually), links are fine; **only screws up at server root dir**
- Should've mentioned: I've got my own special-snowflake way of organizing my server, Apaxy, etc.  This is my directory structure:

```
C:/
+-- Dropbox/
|   +-- GitHub/
|   |   +-- AdamWhitcroft/
|   |   |   +-- apaxy-master/
|   |   |   +-- apaxy-master.zip
|   |   |   +-- batch-master.zip
|   |   ...
|   ...
|   +-- xampp-5.6.30/
|   +-- .htaccess
```
I've got a _ton_ of repos archived, and Apaxy is one of them.
As a result, my .htaccess file looks like this:
```
...
AddIcon /GitHub/AdamWhitcroft/apaxy-master/apaxy/theme/icons/blank.png ^^BLANKICON^^
AddIcon /GitHub/AdamWhitcroft/apaxy-master/apaxy/theme/icons/folder.png ^^DIRECTORY^^
AddIcon /GitHub/AdamWhitcroft/apaxy-master/apaxy/theme/icons/folder-home.png ..
...
```

Once again, using _window.location.href_ and _window.location.host_ seems to fix the footer script on localhost; I'll try it on Google Cloud later today.

**Comment by duncanplatt** [comment] 2017-09-05 09:24
I am glad to hear, @carlos-jenkins!

**Comment by oupala** [comment] 2018-02-22 22:48
Can we close this issue?

**Comment by oupala** [comment] 2018-02-27 20:50
Closing this issue as it is a duplicate of #100.

**Closed by oupala** 2018-02-27 20:50 UTC
Labels: duplicate, good first issue, help wanted, question
