### ISSUE TITLE
links rewritten to //uri when in root level

### ISSUE THREAD

**Issue by commonpike** [oupala/apaxy#100] opened 2017-11-01 13:36 UTC
If you apply this on a domain root (https://mydomain.com/) the little javascript in footer.html rewrites the links to start with // instead of slash, causing the browser to go to, for example, //README.md, which becomes https://README.md which doesn't exist.

I just disabled that whole javascript for now. I think .. apache is removing the trailing slash already

Otherwise, tis a beauty, thanks!

**Comment by rivermont** [comment] 2017-11-02 01:00
Nice find. I don't have this in root so I can't test but I can see this getting bad somewhere.

**Comment by harpreetsb** [comment] 2017-12-08 12:02
same for me

**Comment by damianperera** [comment] 2017-12-12 05:57
Same for me

**Comment by damianperera** [comment] 2017-12-12 06:12
This issue can be fixed by replacing the anchor href replacement code in `footer.html`'s JS script
(`a.href`) with the following snippet:

`a.href = uri + '/' + a.getAttribute('href',2);`

**Comment by oupala** [comment] 2018-02-22 22:53
The file is now `apaxy.js`.

Should we apply the fix?

**Comment by damianperera** [comment] 2018-02-23 01:30
@oupala yes please :)

**Comment by oupala** [comment] 2018-02-23 21:41
I'd like to see someone else confirm the bug, and the fix.

@ jordanbancino would you kind to test that?

**Comment by jordanbancino** [comment] 2018-02-24 02:57
Yeah, no problem. I'll work on it later this week when I have time.

**Comment by jordanbancino** [comment] 2018-02-25 01:19
Ok. Here's what I found:

This bug is indeed a problem with my installation. As for the fix, unless I applied it wrong, it does not work. I will clone and install @damianperera's version later this week, as they seem to have fixed it, judging by the commit reference.

**Comment by jordanbancino** [comment] 2018-02-26 21:02
I am using Chrome.

**Comment by oupala** [comment] 2018-02-27 20:38
Issue #100 and issue #80 are the same.

Both fix are very similar.

**Comment by oupala** [comment] 2018-11-23 08:32
Should we close the issue?

**Comment by oupala** [comment] 2018-11-27 14:38
The issue is fixed in the development branch a release will soon be published.

**Closed by oupala** 2018-11-27 14:38 UTC
Labels: bug, good first issue, help wanted
